//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjectCheck.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PProfile
    {
        public int Profileid { get; set; }
        public string Country { get; set; }
        public int HighestScore { get; set; }
        public string role { get; set; }
        public string BestBowling { get; set; }
        public Nullable<int> Tid { get; set; }
        public Nullable<int> Pid { get; set; }
    
        public virtual Player Player { get; set; }
        public virtual Team Team { get; set; }
    }
}
